# Generated by Django 2.2.7 on 2019-12-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_property', models.CharField(max_length=40, verbose_name='Свойство')),
                ('number', models.IntegerField(unique=True, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Правила',
            },
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=80, unique=True, verbose_name='Модель')),
                ('price', models.CharField(max_length=30, verbose_name='Цена')),
                ('display_size', models.CharField(max_length=30, verbose_name='Размер экрана')),
                ('display_resolution', models.CharField(max_length=12, verbose_name='Разрешение экрана')),
                ('display_technology', models.CharField(max_length=20, verbose_name='Матрица экрана')),
                ('os_version', models.CharField(max_length=30, verbose_name='Версия ОС')),
                ('cellular', models.CharField(max_length=20, verbose_name='Мобильная связь')),
                ('storage_capacity', models.CharField(max_length=10, verbose_name='Объем внутренней памяти')),
                ('ram_capacity', models.CharField(max_length=15, verbose_name='Объем ОЗУ')),
                ('battery_life', models.CharField(max_length=10, verbose_name='Время работы батареи')),
                ('camera', models.CharField(max_length=40, verbose_name='Камера')),
                ('thickness', models.CharField(max_length=20, verbose_name='Толщина устройства')),
                ('weight', models.CharField(max_length=15, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Планшет',
                'verbose_name_plural': 'Планшеты',
            },
        ),
    ]
