# Generated by Django 2.2.7 on 2019-12-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_translation',
            field=models.CharField(default='', max_length=40, verbose_name='Перевод'),
            preserve_default=False,
        ),
    ]
