# Generated by Django 2.2.7 on 2019-12-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property_property_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablet',
            name='manufacturer',
            field=models.CharField(default='', max_length=30, verbose_name='Производитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablet',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
